---
# tasks file for roles/apache2

- name: Installation of Apache2
  ansible.builtin.apt:
    name: apache2
    state: present
  register: result_apache2

- name: show result_apache2
  debug:
    var: result_apache2

- name: Already installed
  debug:
    msg: "Apache2 is already installed"
  when: result_apache2.changed == false

- name: Restart Apache2
  service:
    name: apache2
    state: restarted
  when: result_apache2.changed == true


- name: Check that you can connect (GET) to a page and it returns a status 200
  ansible.builtin.uri:
    url: http://localhost
  status_code: 200
  debug:
    msg: "Apache is in started mode"
#  when:
#    return_content: false
#  register: this
#  failed_when: "apache is off mode "



      #- name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
      #ansible.builtin.uri:
      # url: http://localhost
      # return_content: true
      # register: this
      #failed_when: "'AWESOME' not in this.content
