---
# tasks file for roles/firewall

- name: Installation of iptables
  ansible.builtin.apt:
    name: iptables
    state: present
  register: result_iptables

- name: show result_iptables
  debug:
    var: result_iptables

- name: Already installed
  debug:
    msg: "iptables is already installed"
  when: result_iptables.changed == false

- name: Allow port 80 on the firewall
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT

